version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/docker/janus"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/docker/proxy"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/docker/server"
    schedule:
      interval: "daily"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    groups:
      etcd:
        patterns:
        - "go.etcd.io*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/docs"
    schedule:
      interval: "daily"
