name: check-continentmap

on:
  schedule:
    - cron: "0 2 * * SUN"

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check continentmap
      run: make check-continentmap
