name: docker-compose

on:
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/docker-compose.yml'
      - 'docker-compose.yml'
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/docker-compose.yml'
      - 'docker-compose.yml'

permissions:
  contents: read

jobs:
  pull:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Pull Docker images
        run: docker-compose -f docker/docker-compose.yml pull

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker images
        run: docker-compose -f docker/docker-compose.yml build
