name: Go Vulnerability Checker
on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/govuln.yml'
      - '**.go'
      - 'go.*'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/govuln.yml'
      - '**.go'
      - 'go.*'
  schedule:
    - cron: "0 2 * * SUN"

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - "1.21"
          - "1.22"
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - run: date

    - name: Install dependencies
      run: |
        sudo apt -y update && sudo apt -y install protobuf-compiler
        make common

    - name: Install and run govulncheck
      run: |
        set -euo pipefail
        go install golang.org/x/vuln/cmd/govulncheck@latest
        govulncheck ./...
