name: lint

on:
  push:
    branches: [ master ]
    paths:
      - '**.go'
      - 'go.*'
  pull_request:
    branches: [ master ]
    paths:
      - '**.go'
      - 'go.*'

jobs:
  lint:
    name: golang
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"
          echo "::set-output name=go-version::$(go version | cut -d ' ' -f 3)"

      - name: Go build cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-${{ steps.go-cache-paths.outputs.go-version }}-build-${{ hashFiles('**/go.mod', '**/go.sum') }}

      - name: Go mod cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-${{ steps.go-cache-paths.outputs.go-version }}-mod-${{ hashFiles('**/go.mod', '**/go.sum') }}

      - name: Install dependencies
        run: |
          make common

      - name: lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: latest
